# Generated by Django 4.2.29 on 2026-03-18 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('room_type', models.CharField(choices=[('conference', 'Конференц-зал'), ('office', 'Офіс'), ('event', 'Зал для заходів'), ('coworking', 'Коворкінг')], max_length=20, verbose_name='Тип')),
                ('capacity', models.PositiveIntegerField(verbose_name='Вмістимість (осіб)')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна за день (грн)')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Кімната',
                'verbose_name_plural': 'Кімнати',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата початку')),
                ('end_date', models.DateField(verbose_name='Дата завершення')),
                ('status', models.CharField(choices=[('pending', 'Очікує підтвердження'), ('confirmed', 'Підтверджено'), ('cancelled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.room', verbose_name='Кімната')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Бронювання',
                'verbose_name_plural': 'Бронювання',
                'ordering': ['-created_at'],
            },
        ),
    ]
